### ISSUE TITLE
Alternative Implementation

### ISSUE THREAD

**Issue by adambirse** [adam-mapstone/coding-exercises#3]
https://github.com/adam-mapstone/coding-exercises/blob/4370b06cda7294fe9e8d845a577b4fa10ae12d78/src/main/java/section5/codingexecises/FirstLastDigitSum.java#L21

Lets change the implementation (keeping the method signature the same.  Instead of using a loop.  Convert the int to a string to extract the first and last digits to get the answer

**Comment by adam-mapstone** [comment]
Updated.

- I've updated the int(s) to string using toString
- Used substring to look for the first and last value
- Then returned the values as Integer and then sum the two values
