### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by adambirse** [adam-mapstone/coding-exercises#4]
https://github.com/adam-mapstone/coding-exercises/blob/4370b06cda7294fe9e8d845a577b4fa10ae12d78/src/main/java/section5/codingexecises/LeapYear.java#L12

I know you are limited by the Udemy course in how you write these methods, but I find this  very difficult to read.  Refactor it to make it more readable.   Your goal is to get rid of the comment and have self documenting code.

**Comment by adam-mapstone** [comment]
Updated. Refactored and added a v2 solution to show an alternative way of doing it. Let me know which one you find more readable.
