### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by adambirse** [adam-mapstone/coding-exercises#6]
https://github.com/adam-mapstone/coding-exercises/blob/4370b06cda7294fe9e8d845a577b4fa10ae12d78/src/main/java/section5/codingexecises/TeenNumberChecker.java#L19

How would you make this more readable?

**Comment by adam-mapstone** [comment]
Updated. I've moved each OR onto its own line and added parentheses for extra readability. Never enough parentheses, right?

**Comment by adambirse** [comment]
Spoke to you about why this isnt clearer.
