### ISSUE TITLE
Code Review - Number to Word

### ISSUE THREAD

**Issue by adambirse** [adam-mapstone/coding-exercises#7]
https://github.com/adam-mapstone/coding-exercises/blob/358f613af4c33e623b4cbafd1fe2814b14259e9b/src/main/java/section6/codingexercise/NumberToWords.java#L4

So functionally this looks fine I have a few review comments though.

- Line 7.  Good practice is to get into the habbit of making sure your log messages are proper sentences.  I think this should be "Invalid Value." As I side not a useful thing I always find is that when you are debugging code (and you may put println() statements in to help understand) is to prefix them with your initials e.g. "AJB: What is happening here?" this gives you something to search for and delete before you commit code.
- Line 10 and 11.  I dont think these variables are particularly well defined, consider alternative names
- Switch statement: ALWAYS include a default.  I know you are protected by the remainder operation that calculates last digit but always code defensively.
- I had to read the requirements for this challenge to try and understand what was going on here. Similar to what we did yesterday with calculating leap year have a go at refactoring this to make it more readable. This is subjective but we can compare my solution for this and discuss.
- I think the method is 'upside down' in terms of readability. (again this can be viewed as personal preference.  I would structure this as follows

numberToWords {
 
if (number >= 0) {
    // Do stuff 
} else {
    System.out.println("Invalid value.");
}

- Line 61 (getDigitCount() ) if statements should ALWAYS have braces even if there is only one statement.
- reverse() and getDigitCount() should be private not public.  Although they CAN be public as they can be used independently without any side effects.  I would suggest getting into the practice of only making public what needs to be.

**Comment by adam-mapstone** [comment]
Refactor complete - changes committed.
