### ISSUE TITLE
Review comments - Diagonal star

### ISSUE THREAD

**Issue by adambirse** [adam-mapstone/coding-exercises#8]
https://github.com/adam-mapstone/coding-exercises/blob/02e0f54ed9619a79df855d619f9ae4299fad3c2e/src/main/java/section6/codingexercise/DiagonalStar.java#L9

Good, but name variables appropriately. this is much more readable if instead of using i and j.  You call the variables x and y

**Comment by adam-mapstone** [comment]
Will update. For my own benefit, why is x and y more readable then i and j? I thought i, j, k etc. were typically used for temporary iteration variables.

**Comment by adam-mapstone** [comment]
Fair enough, understood. Variables updated.
